# Data preparation

## Interactions

In [1]:
import os
import pandas as pd
import numpy as np

pd.options.mode.copy_on_write = True
path = os.path.join("data", "RAW_interactions.csv")
inter = pd.read_csv(path, engine="python")
inter.head()

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

In [2]:
inter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1132367 entries, 0 to 1132366
Data columns (total 5 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1132367 non-null  int64
 1   recipe_id  1132367 non-null  int64
 2   date       1132367 non-null  object
 3   rating     1132367 non-null  int64
 4   review     1132198 non-null  object
dtypes: int64(3), object(2)
memory usage: 43.2+ MB

In [3]:
inter = inter.dropna()
inter.describe()["rating"]

count    1.132198e+06
mean     4.410971e+00
std      1.264812e+00
min      0.000000e+00
25%      4.000000e+00
50%      5.000000e+00
75%      5.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

## Recipes

In [4]:
path = os.path.join("data", "RAW_recipes.csv")
recipes = pd.read_csv(path, index_col="id")
recipes.head()

,name,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
id,,,,,,,,,,,
137739,arriba baked winter squash mexican style,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
31490,a bit different breakfast pizza,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
112140,all in the kitchen chili,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
59389,alouette potatoes,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
44061,amish tomato ketchup for canning,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [5]:
recipes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 231637 entries, 137739 to 298509
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            231636 non-null  object
 1   minutes         231637 non-null  int64
 2   contributor_id  231637 non-null  int64
 3   submitted       231637 non-null  object
 4   tags            231637 non-null  object
 5   nutrition       231637 non-null  object
 6   n_steps         231637 non-null  int64
 7   steps           231637 non-null  object
 8   description     226658 non-null  object
 9   ingredients     231637 non-null  object
 10  n_ingredients   231637 non-null  int64
dtypes: int64(4), object(7)
memory usage: 21.2+ MB

# Hands-on work

In [6]:
inter = inter.loc[inter["rating"] == 5]
rcp_init = recipes[:5000]

itr_init = inter[inter["recipe_id"].isin(rcp_init.index)]
itr_init

,user_id,recipe_id,date,rating,review
35,6258,20930,2002-07-09,5,"Jan, what an interesting combination of flavor..."
36,102602,20930,2003-10-26,5,"Jan, we love your pasta salad, it's delicious...."
81,52476,181765,2006-08-15,5,We have been eating this bbq sauce for years! ...
82,37722,181765,2007-03-12,5,This is excellent and the same recipe I've alw...
133,386585,278406,2008-09-29,5,This is a great variation on the classic Reube...
...,...,...,...,...,...
1131152,313014,83062,2007-09-09,5,Very good! Moist and delicious. I didn't have...
1132081,296809,157534,2006-07-04,5,Such a neat idea! 2 of us & less than 30 min –...
1132083,80980,157534,2006-10-20,5,I found the flavor of this dish to be very goo...
1132203,282678,157534,2007-03-22,5,Awesome recipe! So easy and flavorful. The tas...
1132205,1269180,157534,2014-05-03,5,Amazing! Ended up with 3 adult and 2 toddler s...